//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNTS_TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNTS_TEACHER()
        {
            this.GIANGVIENs = new HashSet<GIANGVIEN2>();
        }
    
        public string AccID_Tea { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public Nullable<int> Remember { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIANGVIEN2> GIANGVIENs { get; set; }
    }
}
