//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public string AdmID { get; set; }
        public string ACCID { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string ChucVu { get; set; }
    
        public virtual ACCOUNTS_ADMIN ACCOUNTS_ADMIN { get; set; }
    }
}
