//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public string ID { get; set; }
        public string HOTEN { get; set; }
        public string CHUCVU { get; set; }
        public Nullable<int> Luong { get; set; }
        public Nullable<int> LuongDay { get; set; }
        public Nullable<int> PhuCap { get; set; }
        public Nullable<int> TienThuong { get; set; }
        public Nullable<int> TienBaoHiem { get; set; }
        public Nullable<int> Tongluong { get; set; }
        public int THANG { get; set; }
    }
}
