//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHSACHLOP
    {
        public string MaLop { get; set; }
        public string HVID { get; set; }
        public Nullable<double> DiemGiuaKy { get; set; }
        public Nullable<double> DiemCuoiKy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual HOCVIEN1 HOCVIEN { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
