//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FULL_THONGTIN
    {
        public string ID { get; set; }
        public string HOTEN { get; set; }
        public string ChucVu { get; set; }
        public string ACCID { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
    }
}
