//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIEN1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOCVIEN1()
        {
            this.DANHSACHLOPs = new HashSet<DANHSACHLOP>();
            this.LICHSUTHUTIENs = new HashSet<LICHSUTHUTIEN>();
        }
    
        public string HVID { get; set; }
        public string ACCID { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public byte[] AVATAR { get; set; }
        public Nullable<int> TienTaiKhoan { get; set; }
        public string ChucVu { get; set; }
    
        public virtual ACCOUNTS_STUDENT ACCOUNTS_STUDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHLOP> DANHSACHLOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUTHUTIEN> LICHSUTHUTIENs { get; set; }
    }
}
