//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPTHU
    {
        public string MaThu { get; set; }
        public string IDGui { get; set; }
        public string ChucVu { get; set; }
        public string IDNhan { get; set; }
        public string TieuDe { get; set; }
        public string Noidung { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public Nullable<bool> DanhDau { get; set; }
    }
}
