//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUTHUTIEN
    {
        public string MaPT { get; set; }
        public string HVID { get; set; }
        public string MaLop { get; set; }
        public string LoaiTien { get; set; }
        public Nullable<int> SoTienDong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
    
        public virtual HOCVIEN1 HOCVIEN { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
    }
}
