//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHHOC
    {
        public string MaLop { get; set; }
        public string Thu { get; set; }
        public string Ca { get; set; }
        public string Phong { get; set; }
    
        public virtual GIOHOC GIOHOC { get; set; }
        public virtual LOPHOC LOPHOC { get; set; }
        public virtual PHONGHOC PHONGHOC { get; set; }
    }
}
