//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPDANGKI
    {
        public string MaLop { get; set; }
        public string TenMon { get; set; }
        public string TenKH { get; set; }
        public string SoBuoiTrongTuan { get; set; }
        public string HocPhi { get; set; }
        public Nullable<double> DiemTBQuaMon { get; set; }
        public string SoHocVien { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string TrangThai { get; set; }
        public string Thu { get; set; }
        public string Ca { get; set; }
        public string Phong { get; set; }
        public string HOTEN { get; set; }
        public string GiangVien { get; set; }
        public Nullable<int> TTMoLop { get; set; }
        public Nullable<int> XacNhan { get; set; }
    }
}
