//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOPHOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOPHOC()
        {
            this.DANHSACHLOPs = new HashSet<DANHSACHLOP>();
            this.LICHHOCs = new HashSet<LICHHOC>();
            this.LICHSUTHUTIENs = new HashSet<LICHSUTHUTIEN>();
        }
    
        public string MaLop { get; set; }
        public string MaKH { get; set; }
        public string TenMon { get; set; }
        public string TenMonGon { get; set; }
        public string SoBuoiTrongTuan { get; set; }
        public string HocPhi { get; set; }
        public Nullable<double> DiemTBQuaMon { get; set; }
        public string GiangVien { get; set; }
        public string SoHocVien { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> Luong { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> TTMoLop { get; set; }
        public Nullable<int> XacNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHSACHLOP> DANHSACHLOPs { get; set; }
        public virtual GIANGVIEN2 GIANGVIEN1 { get; set; }
        public virtual KHOAHOC KHOAHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHHOC> LICHHOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUTHUTIEN> LICHSUTHUTIENs { get; set; }
    }
}
